language: ruby

script: "rake travis"

rvm:
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - develop

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libpcap-dev -qq
 - gem install bundler
